services:
  - type: web
    name: aimoral
    runtime: python
    runtimeVersion: 3.13
    buildCommand: bash build.sh
    startCommand: gunicorn project.wsgi:application --bind 0.0.0.0:$PORT --workers 4
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project.settings
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: "*.render.com"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: true
    autoDeploy: true

databases:
  - name: aimoraldb
    databaseName: aimoraldb
    user: aimoraluser
    plan: free
