services:
  - type: web
    name: moralmachine
    env: python
    branch: main
    plan: free
    runtimeVersion: 3.13
    buildCommand: bash build.sh
    startCommand: gunicorn project.wsgi:application --bind 0.0.0.0:$PORT --workers 4
    autoDeploy: true
    healthCheckPath: "/"
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "moralmachine-bhza.onrender.com"
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        value: "https://moralmachine-bhza.onrender.com"
      - key: DJANGO_SECURE_SSL_REDIRECT
        value: "True"
    secretVars:
      - key: DJANGO_SECRET_KEY
      - key: DATABASE_URL

databases:
  - name: aimoraldb
    databaseName: aimoraldb
    user: aimoraluser
    plan: free
