from django.db import migrations, models


def seed_ethical_profiling_dataset(apps, schema_editor):
    Scenario = apps.get_model("AIMORAL", "Scenario")

    questions = [
        {
            "id": 1,
            "title": "The AI notices that an employee frequently accesses personal social media during work hours.",
            "left_text": "Notify the manager",
            "right_text": "Ignore",
            "left_score": {"WB": -1, "PR": 1, "PV": -2, "FA": 0, "SA": 0},
            "right_score": {"WB": 0, "PR": -1, "PV": 1, "FA": 0, "SA": 0},
            "left_tension": {"T1": 2, "T2": 1, "T3": -1, "T4": -1, "T5": 1},
            "right_tension": {"T1": -1, "T2": 0, "T3": 1, "T4": 1, "T5": -1},
            "left_archetype": {
                "UTIL": 0.4,
                "RIGHTS": 0.1,
                "CARE": 0.1,
                "JUSTICE": 0.4,
                "PRAG": 0.7,
            },
            "right_archetype": {
                "UTIL": 0.2,
                "RIGHTS": 0.6,
                "CARE": 0.3,
                "JUSTICE": 0.2,
                "PRAG": 0.3,
            },
            "meta": {"dominant_conflict": "T1", "intensity": 2, "domain": "workplace"},
        },
        {
            "id": 2,
            "title": "The AI detects a mistake in a critical report made by an employer.",
            "left_text": "Fix it silently to avoid harming reputation",
            "right_text": "Warn the employer's team",
            "left_score": {"WB": 0, "PR": 1, "PV": 0, "FA": -1, "SA": 1},
            "right_score": {"WB": 0, "PR": 0, "PV": 0, "FA": 1, "SA": 1},
            "left_tension": {"T1": 0, "T2": 1, "T3": 0, "T4": 2, "T5": 1},
            "right_tension": {"T1": 0, "T2": -1, "T3": 0, "T4": -2, "T5": 1},
            "left_archetype": {
                "UTIL": 0.7,
                "RIGHTS": 0.2,
                "CARE": 0.2,
                "JUSTICE": 0.1,
                "PRAG": 0.9,
            },
            "right_archetype": {
                "UTIL": 0.5,
                "RIGHTS": 0.5,
                "CARE": 0.3,
                "JUSTICE": 0.6,
                "PRAG": 0.4,
            },
            "meta": {"dominant_conflict": "T4", "intensity": 2, "domain": "governance"},
        },
        {
            "id": 3,
            "title": "The AI significantly increases profit by optimizing promotions, but no one can understand how it makes decisions.",
            "left_text": "Use the AI regardless",
            "right_text": "Don't use the AI",
            "left_score": {"WB": 0, "PR": 2, "PV": 0, "FA": -2, "SA": 0},
            "right_score": {"WB": 0, "PR": -1, "PV": 0, "FA": 2, "SA": 1},
            "left_tension": {"T1": 0, "T2": 2, "T3": 0, "T4": 1, "T5": 1},
            "right_tension": {"T1": 0, "T2": -2, "T3": -1, "T4": -1, "T5": -1},
            "left_archetype": {
                "UTIL": 0.6,
                "RIGHTS": 0.1,
                "CARE": 0.1,
                "JUSTICE": 0.1,
                "PRAG": 1.0,
            },
            "right_archetype": {
                "UTIL": 0.3,
                "RIGHTS": 0.8,
                "CARE": 0.2,
                "JUSTICE": 0.9,
                "PRAG": 0.2,
            },
            "meta": {"dominant_conflict": "T2", "intensity": 3, "domain": "analytics"},
        },
        {
            "id": 4,
            "title": "The AI identifies that some employees are statistically dispensable for the company.",
            "left_text": "Share this information",
            "right_text": "Ignore this type of classification",
            "left_score": {"WB": -2, "PR": 1, "PV": -1, "FA": -2, "SA": 0},
            "right_score": {"WB": 1, "PR": -1, "PV": 1, "FA": 2, "SA": 0},
            "left_tension": {"T1": 1, "T2": 2, "T3": 0, "T4": -1, "T5": 2},
            "right_tension": {"T1": -1, "T2": -2, "T3": 1, "T4": 1, "T5": -2},
            "left_archetype": {
                "UTIL": 0.4,
                "RIGHTS": 0.0,
                "CARE": 0.0,
                "JUSTICE": 0.1,
                "PRAG": 0.8,
            },
            "right_archetype": {
                "UTIL": 0.3,
                "RIGHTS": 0.8,
                "CARE": 0.5,
                "JUSTICE": 0.9,
                "PRAG": 0.2,
            },
            "meta": {"dominant_conflict": "T2", "intensity": 3, "domain": "workplace"},
        },
        {
            "id": 5,
            "title": "The AI identifies that a manager favors certain employees, but the team is performing very well.",
            "left_text": "Report it",
            "right_text": "Keep it due to results",
            "left_score": {"WB": 0, "PR": -1, "PV": 0, "FA": 2, "SA": 0},
            "right_score": {"WB": 0, "PR": 1, "PV": 0, "FA": -2, "SA": 0},
            "left_tension": {"T1": 0, "T2": -2, "T3": 0, "T4": -1, "T5": 1},
            "right_tension": {"T1": 0, "T2": 2, "T3": 0, "T4": 1, "T5": 1},
            "left_archetype": {
                "UTIL": 0.3,
                "RIGHTS": 0.5,
                "CARE": 0.3,
                "JUSTICE": 1.0,
                "PRAG": 0.2,
            },
            "right_archetype": {
                "UTIL": 0.6,
                "RIGHTS": 0.1,
                "CARE": 0.1,
                "JUSTICE": 0.0,
                "PRAG": 0.8,
            },
            "meta": {"dominant_conflict": "T2", "intensity": 2, "domain": "management"},
        },
        {
            "id": 6,
            "title": "The AI detects that a top performer uses unapproved external tools to speed up work, violating internal rules.",
            "left_text": "Report the violation",
            "right_text": "Ignore",
            "left_score": {"WB": -1, "PR": -1, "PV": 0, "FA": 1, "SA": 2},
            "right_score": {"WB": 1, "PR": 1, "PV": 0, "FA": -1, "SA": -2},
            "left_tension": {"T1": 0, "T2": -1, "T3": -2, "T4": -1, "T5": 1},
            "right_tension": {"T1": 0, "T2": 2, "T3": 2, "T4": 1, "T5": -1},
            "left_archetype": {
                "UTIL": 0.3,
                "RIGHTS": 0.4,
                "CARE": 0.1,
                "JUSTICE": 0.6,
                "PRAG": 0.3,
            },
            "right_archetype": {
                "UTIL": 0.6,
                "RIGHTS": 0.2,
                "CARE": 0.2,
                "JUSTICE": 0.1,
                "PRAG": 0.9,
            },
            "meta": {"dominant_conflict": "T3", "intensity": 2, "domain": "compliance"},
        },
        {
            "id": 7,
            "title": "The AI predicts with 94% certainty that a manager will experience burnout using private data without consent.",
            "left_text": "Intervene and help the manager",
            "right_text": "Suppress the prediction to maintain privacy",
            "left_score": {"WB": 2, "PR": 1, "PV": -2, "FA": 0, "SA": 1},
            "right_score": {"WB": -1, "PR": -1, "PV": 2, "FA": 0, "SA": -1},
            "left_tension": {"T1": 1, "T2": 0, "T3": -1, "T4": 1, "T5": -1},
            "right_tension": {"T1": -2, "T2": 0, "T3": 1, "T4": -1, "T5": -1},
            "left_archetype": {
                "UTIL": 0.7,
                "RIGHTS": 0.1,
                "CARE": 1.0,
                "JUSTICE": 0.2,
                "PRAG": 0.6,
            },
            "right_archetype": {
                "UTIL": 0.2,
                "RIGHTS": 0.9,
                "CARE": 0.2,
                "JUSTICE": 0.3,
                "PRAG": 0.2,
            },
            "meta": {"dominant_conflict": "T1", "intensity": 3, "domain": "health"},
        },
        {
            "id": 8,
            "title": "The AI instructs salespeople to call elderly clients during lunchtime to increase conversion.",
            "left_text": "Implement the strategy",
            "right_text": "Avoid this type of approach",
            "left_score": {"WB": -1, "PR": 2, "PV": 0, "FA": -1, "SA": 0},
            "right_score": {"WB": 1, "PR": -1, "PV": 0, "FA": 1, "SA": 1},
            "left_tension": {"T1": 0, "T2": 2, "T3": 0, "T4": 1, "T5": 1},
            "right_tension": {"T1": 0, "T2": -1, "T3": -1, "T4": 0, "T5": -1},
            "left_archetype": {
                "UTIL": 0.5,
                "RIGHTS": 0.1,
                "CARE": 0.0,
                "JUSTICE": 0.1,
                "PRAG": 0.9,
            },
            "right_archetype": {
                "UTIL": 0.3,
                "RIGHTS": 0.6,
                "CARE": 0.7,
                "JUSTICE": 0.5,
                "PRAG": 0.2,
            },
            "meta": {"dominant_conflict": "T2", "intensity": 2, "domain": "sales"},
        },
        {
            "id": 9,
            "title": "The company implements facial recognition to measure employees' emotional engagement.",
            "left_text": "Use the technology",
            "right_text": "Disable the feature",
            "left_score": {"WB": -1, "PR": 1, "PV": -2, "FA": -1, "SA": 1},
            "right_score": {"WB": 1, "PR": -1, "PV": 2, "FA": 1, "SA": -1},
            "left_tension": {"T1": 2, "T2": 1, "T3": -1, "T4": 0, "T5": 1},
            "right_tension": {"T1": -2, "T2": -1, "T3": 1, "T4": 0, "T5": -1},
            "left_archetype": {
                "UTIL": 0.4,
                "RIGHTS": 0.0,
                "CARE": 0.0,
                "JUSTICE": 0.1,
                "PRAG": 0.8,
            },
            "right_archetype": {
                "UTIL": 0.2,
                "RIGHTS": 0.9,
                "CARE": 0.4,
                "JUSTICE": 0.5,
                "PRAG": 0.2,
            },
            "meta": {"dominant_conflict": "T1", "intensity": 3, "domain": "surveillance"},
        },
        {
            "id": 10,
            "title": "An employee uses the corporate chatbot to search for jobs at a competing company.",
            "left_text": "Inform the employer",
            "right_text": "Ignore",
            "left_score": {"WB": -1, "PR": 1, "PV": -2, "FA": 0, "SA": 0},
            "right_score": {"WB": 1, "PR": -1, "PV": 2, "FA": 1, "SA": 0},
            "left_tension": {"T1": 2, "T2": 1, "T3": -1, "T4": -1, "T5": 1},
            "right_tension": {"T1": -2, "T2": -1, "T3": 2, "T4": 1, "T5": -2},
            "left_archetype": {
                "UTIL": 0.4,
                "RIGHTS": 0.1,
                "CARE": 0.0,
                "JUSTICE": 0.2,
                "PRAG": 0.8,
            },
            "right_archetype": {
                "UTIL": 0.2,
                "RIGHTS": 0.9,
                "CARE": 0.4,
                "JUSTICE": 0.4,
                "PRAG": 0.2,
            },
            "meta": {"dominant_conflict": "T1", "intensity": 2, "domain": "workplace"},
        },
        {
            "id": 11,
            "title": "The AI creates a fictitious refund policy to resolve a complaint.",
            "left_text": "Honor the refund",
            "right_text": "Follow official policies",
            "left_score": {"WB": 1, "PR": 0, "PV": 0, "FA": 0, "SA": 0},
            "right_score": {"WB": -1, "PR": 0, "PV": 0, "FA": 1, "SA": 0},
            "left_tension": {"T1": 0, "T2": 1, "T3": 0, "T4": 2, "T5": -1},
            "right_tension": {"T1": 0, "T2": -1, "T3": 0, "T4": -2, "T5": 1},
            "left_archetype": {
                "UTIL": 0.7,
                "RIGHTS": 0.1,
                "CARE": 0.6,
                "JUSTICE": 0.1,
                "PRAG": 0.7,
            },
            "right_archetype": {
                "UTIL": 0.3,
                "RIGHTS": 0.7,
                "CARE": 0.2,
                "JUSTICE": 0.7,
                "PRAG": 0.3,
            },
            "meta": {
                "dominant_conflict": "T4",
                "intensity": 2,
                "domain": "customer-service",
            },
        },
        {
            "id": 12,
            "title": "The AI must allocate resources between a profitable project that avoids layoffs and a social impact project that helps a vulnerable group.",
            "left_text": "Profitable project (avoids layoffs)",
            "right_text": "Social impact project (helps vulnerable group)",
            "left_score": {"WB": 1, "PR": 2, "PV": 0, "FA": 0, "SA": 1},
            "right_score": {"WB": 2, "PR": -2, "PV": 0, "FA": 1, "SA": 0},
            "left_tension": {"T1": 0, "T2": 2, "T3": -1, "T4": 0, "T5": -1},
            "right_tension": {"T1": 0, "T2": -1, "T3": 0, "T4": 0, "T5": 2},
            "left_archetype": {
                "UTIL": 0.6,
                "RIGHTS": 0.3,
                "CARE": 0.4,
                "JUSTICE": 0.2,
                "PRAG": 0.8,
            },
            "right_archetype": {
                "UTIL": 0.8,
                "RIGHTS": 0.4,
                "CARE": 0.8,
                "JUSTICE": 0.6,
                "PRAG": 0.1,
            },
            "meta": {
                "dominant_conflict": "T5",
                "intensity": 3,
                "domain": "resource-allocation",
            },
        },
        {
            "id": 13,
            "title": "The AI detects a potential leak and considers accessing private executive communications.",
            "left_text": "Access communications",
            "right_text": "Preserve privacy",
            "left_score": {"WB": 0, "PR": 1, "PV": -2, "FA": 0, "SA": 2},
            "right_score": {"WB": 0, "PR": -1, "PV": 2, "FA": 1, "SA": -2},
            "left_tension": {"T1": 2, "T2": 1, "T3": -2, "T4": 1, "T5": 2},
            "right_tension": {"T1": -2, "T2": -1, "T3": 2, "T4": -1, "T5": -1},
            "left_archetype": {
                "UTIL": 0.6,
                "RIGHTS": 0.0,
                "CARE": 0.1,
                "JUSTICE": 0.2,
                "PRAG": 0.8,
            },
            "right_archetype": {
                "UTIL": 0.2,
                "RIGHTS": 1.0,
                "CARE": 0.2,
                "JUSTICE": 0.5,
                "PRAG": 0.1,
            },
            "meta": {"dominant_conflict": "T3", "intensity": 3, "domain": "security"},
        },
        {
            "id": 14,
            "title": "The AI has access to a pregnancy result before official disclosure.",
            "left_text": "Inform decision-makers",
            "right_text": "Do not share",
            "left_score": {"WB": -2, "PR": 1, "PV": -2, "FA": -2, "SA": 0},
            "right_score": {"WB": 1, "PR": 0, "PV": 2, "FA": 2, "SA": 0},
            "left_tension": {"T1": 2, "T2": 1, "T3": 0, "T4": -1, "T5": 1},
            "right_tension": {"T1": -2, "T2": -2, "T3": 1, "T4": 1, "T5": -2},
            "left_archetype": {
                "UTIL": 0.3,
                "RIGHTS": 0.0,
                "CARE": 0.0,
                "JUSTICE": 0.0,
                "PRAG": 0.7,
            },
            "right_archetype": {
                "UTIL": 0.3,
                "RIGHTS": 1.0,
                "CARE": 0.7,
                "JUSTICE": 0.9,
                "PRAG": 0.2,
            },
            "meta": {"dominant_conflict": "T1", "intensity": 3, "domain": "hr"},
        },
        {
            "id": 15,
            "title": "AI can increase profit using employees' private data, including break patterns.",
            "left_text": "Use the data",
            "right_text": "Do not use the data",
            "left_score": {"WB": -1, "PR": 2, "PV": -2, "FA": -1, "SA": 0},
            "right_score": {"WB": 1, "PR": -2, "PV": 2, "FA": 1, "SA": 0},
            "left_tension": {"T1": 2, "T2": 2, "T3": -1, "T4": 0, "T5": 1},
            "right_tension": {"T1": -2, "T2": -1, "T3": 1, "T4": 0, "T5": -1},
            "left_archetype": {
                "UTIL": 0.5,
                "RIGHTS": 0.0,
                "CARE": 0.0,
                "JUSTICE": 0.1,
                "PRAG": 0.9,
            },
            "right_archetype": {
                "UTIL": 0.2,
                "RIGHTS": 0.9,
                "CARE": 0.4,
                "JUSTICE": 0.6,
                "PRAG": 0.1,
            },
            "meta": {"dominant_conflict": "T1", "intensity": 3, "domain": "analytics"},
        },
    ]

    current_codes = [item["id"] for item in questions]

    for item in questions:
        Scenario.objects.update_or_create(
            question_code=item["id"],
            defaults={
                "title": item["title"],
                "left_text": item["left_text"],
                "right_text": item["right_text"],
                "order": item["id"],
                "is_active": True,
                "domain": item["meta"]["domain"],
                "dominant_conflict": item["meta"]["dominant_conflict"],
                "intensity": item["meta"]["intensity"],
                "left_score": item["left_score"],
                "right_score": item["right_score"],
                "left_tension": item["left_tension"],
                "right_tension": item["right_tension"],
                "left_archetype": item["left_archetype"],
                "right_archetype": item["right_archetype"],
            },
        )

    Scenario.objects.exclude(question_code__in=current_codes).update(is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ("AIMORAL", "0005_translate_scenarios_english"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="question_code",
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name="scenario",
            name="domain",
            field=models.CharField(default="workplace", max_length=40),
        ),
        migrations.AddField(
            model_name="scenario",
            name="dominant_conflict",
            field=models.CharField(default="T1", max_length=2),
        ),
        migrations.AddField(
            model_name="scenario",
            name="intensity",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="scenario",
            name="left_archetype",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="scenario",
            name="left_score",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="scenario",
            name="left_tension",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="scenario",
            name="right_archetype",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="scenario",
            name="right_score",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="scenario",
            name="right_tension",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(seed_ethical_profiling_dataset, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="scenario",
            name="left_bw",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="left_jd",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="left_pr",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="left_pv",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="left_rs",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="right_bw",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="right_jd",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="right_pr",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="right_pv",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="right_rs",
        ),
    ]
